export interface IAssociatedVehicle {
    id: number;
    ez: string;
    make: string;
    mileageInKm: number;
    model: string;
    vin: string;
    hadAccident: boolean;
    accidentDescription?: string | null;
    category: number;
    doors: number;
    enginePowerInHp: number;
    engineSizeInCcm: number;
    fuelType: number;
    transmission: number;
    upholstery: number;
    ac: number;
    coupling: number;
    headlights: number;
    navigation: number;
    parkingAssistance: number;
    sportPackage: number;
    sunRoof: number;
    vehicleHeater: number;
    huReportExists: boolean;
    lastHu: string;
    numKeys: number;
    numPreOwners: number;
    vatIdReportable: boolean;
    urlToAttachment1?: string | null;
    urlToAttachment2?: string | null;
    urlToAttachment3?: string | null;
    additionalDamages: string | null;
    urlToVehicleSummarySheet?: string | null;
    euroNorm?: unknown;
    dimensionWidthInCm?: number | null;
    dimensionHeightInCm?: number | null;
    dimensionLengthInCm?: number | null;
    unloadedWeightInKg?: number | null;
    numSeats?: number | null;
    isReimportedVehicle: boolean;
    datBaseModelRaw?: unknown;
    seriesEquipments: unknown[];
    specialEquipments: unknown[];
    uuid: string;
    origin: number;
    dataSource: number;
    createdAt: Date;
    updatedAt: Date;
    deletedAt?: Date | null;
    lastServiceInspectionDate: string;
    lastServiceInspectionMileage: number;
    isCocDocumentAvailable: boolean;
    countryOfLastRegistration: string | null;
    bodyColorCode: number;
    readyToDrive: number;
    readyToDriveDetails?: unknown;
    hasDamages: boolean;
    damagesDescription?: string | null;
    additionalInfo?: string | null;
    dataWarnings: unknown[];
    serviceHistoryAvailability: number;
    fullServiceHistoryType: number;
    hasMaintenanceBook: boolean;
    attachments: unknown[];
    damages: unknown[];
    equipmentData: unknown[];
    equipmentHighlights: unknown[];
    vehicleImages: { url: string; perspective: number}[];
    tires: unknown[];
    paintState: unknown[];
    technicalState: unknown[];
}