import { IAssociatedVehicle } from './IAssociatedVehicle';
import { ISellerAccount } from './ISellerAccount';
import { ITransportationTask } from './ITransportationTask';

export interface IBuyerAuction {
  id: number;
  label: string;
  endingTime: Date;
  state: number;
  minimumRequiredAsk: number;
  currentHighestBidValue: number;
  numBids: number;
  isRatedByDealership: boolean;
  isPaidByBuyer: boolean;
  locationAddress?: unknown;
  locationCity: string;
  locationZip: string;
  startedAt: Date;
  createdAt: Date;
  updatedAt: Date;
  hotBid: boolean;
  originalMinimumRequiredAsk?: number | null;
  incomingPaymentConfirmedAt?: Date | null;
  outgoingPaymentConfirmedAt?: Date | null;
  purchaseConfirmedAt?: Date | null;
  pickupConfirmedAt?: Date | null;
  isRatedByBuyer: boolean;
  allowInstantPurchase: boolean;
  didEndWithInstantPurchase: boolean;
  instantPurchasePossibleUntil?: Date | null;
  priority?: number | null;
  advertisementHtmlContent?: string | null;
  instantPurchasePrice?: number | null;
  urlToInvoice?: string | null;
  locationCountryCode: string;
  purchaseRejectedAt?: Date | null;
  involvedInternalResolverUserRole?: string | null;
  internalReferenceText?: string | null;
  sellerIban?: string | null;
  startingBidValue: number;
  invoiceReference?: string | null;
  uuid: string;
  _fk_uuid_vehicle: string;
  _fk_uuid_sellerUser: string;
  _fk_uuid_highestBiddingBuyerUser?: string | null;
  _fk_uuid_involvedInternalUser?: string | null;
  _fk_uuid_involvedInternalResolverUser?: string | null;
  urlToPickupBuyerDocument?: string | null;
  thirdPartyInvoiceReference?: string | null;
  urlToPaymentSite?: string | null;
  thirdPartyTransferReference?: string | null;
  thirdPartyPayoutReference?: string | null;
  paymentProcess: number;
  pickupPinCodeEnteredAt?: Date | null;
  locationGeoLat?: number | null;
  locationGeoLon?: number | null;
  lastOfferBySeller?: unknown | null;
  isSuspectedCashPayment: boolean;
  type: number;
  _fk_uuid_creatingInternalUser: string;
  counterOfferByBuyer?: unknown | null;
  _fk_uuid_creatingSellerUser?: string | null;
  isTest: boolean;
  thirdPartyVehiclePurchaseInvoiceReference?: string | null;
  displayMinAsk: boolean;
  pickupPinUuid?: string | null;
  pickupPinUuidEnteredAt?: Date | null;
  isLive: boolean;
  amIInvolved: boolean;
  biddingAgentValue: number;
  remainingTimeInSeconds: number;
  remainingTimeForInstantPurchaseInSeconds?: number | null;
  isRejectionWaitPeriodOver: boolean;
  associatedVehicle: IAssociatedVehicle;
  amIHighestBidder: boolean;
  sellerContact?: string | null;
  rating?: number | null;
  transportationTask: ITransportationTask;
  isTransportationAllowedForRegion: boolean;
  isExternalPaymentAllowed: boolean;
  pickupPinCode?: string | null;
  remainingDaysUntilReauctioning?: number | null;
  remainingDaysUntilLatePickup?: number | null;
  latePickupFee?: number | null;
  isTransportationBookingPossible: boolean;
  isExpressPickupAvailable: boolean;
  pickupPossibleInDays?: number | null;
  sellerAccount: ISellerAccount | null;
  amIRegularBuyer: boolean;
  distanceToVehicleInKms: number;
  isMinAskReached: boolean;
  sellerType: number;
  enforceTransportation: boolean;
  isTransportationAvailable: boolean
}