import faker from 'faker';


export const fakeBuyerAuctionsResponse = ({}, count = 1) => {
  let fakeArray = [];
  for (let index = 0; index < count; index++) {
    fakeArray.push({
      id: faker.datatype.number({ min: 1 }),
      label: faker.vehicle.model(),
      state: 2,
      sellerType: 0,
      endingTime: "2021-06-16T10:44:44.587Z",
      minimumRequiredAsk: 18110,
      currentHighestBidValue: 390,
      numBids: 0,
      isRatedByDealership: false,
      isPaidByBuyer: false,
      locationAddress: null,
      locationCity: "",
      locationZip: "80xxx",
      startedAt: "2021-06-15T08:42:46.707Z",
      createdAt: "2021-06-15T08:42:46.400Z",
      updatedAt: "2021-06-15T08:42:47.712Z",
      hotBid: true,
      originalMinimumRequiredAsk: null,
      incomingPaymentConfirmedAt: null,
      outgoingPaymentConfirmedAt: null,
      purchaseConfirmedAt: null,
      pickupConfirmedAt: null,
      isRatedByBuyer: false,
      allowInstantPurchase: false,
      didEndWithInstantPurchase: false,
      instantPurchasePossibleUntil: null,
      priority: 2,
      advertisementHtmlContent: null,
      instantPurchasePrice: null,
      urlToInvoice: null,
      locationCountryCode: "DE",
      purchaseRejectedAt: null,
      involvedInternalResolverUserRole: null,
      internalReferenceText: null,
      sellerIban: null,
      startingBidValue: 390,
      invoiceReference: null,
      uuid: faker.datatype.uuid(),
      _fk_uuid_vehicle: "17b95def-bbfd-40ea-a939-a6ea66a433c7",
      _fk_uuid_sellerUser: "4658acde-f4c2-47b9-ba1d-4f024087611e",
      _fk_uuid_highestBiddingBuyerUser: null,
      _fk_uuid_involvedInternalUser: null,
      _fk_uuid_involvedInternalResolverUser: null,
      urlToPickupBuyerDocument: null,
      thirdPartyInvoiceReference: null,
      urlToPaymentSite: null,
      thirdPartyTransferReference: null,
      thirdPartyPayoutReference: null,
      paymentProcess: 0,
      pickupPinCodeEnteredAt: null,
      locationGeoLat: null,
      locationGeoLon: null,
      lastOfferBySeller: null,
      isSuspectedCashPayment: false,
      type: 0,
      _fk_uuid_creatingInternalUser: "0b3e30b0-ab10-4433-8aea-4b17ac134476",
      counterOfferByBuyer: null,
      _fk_uuid_creatingSellerUser: null,
      isTest: false,
      thirdPartyVehiclePurchaseInvoiceReference: null,
      displayMinAsk: false,
      pickupPinUuid: null,
      pickupPinUuidEnteredAt: null,
      isLive: false,
      amIInvolved: false,
      biddingAgentValue: 0,
      remainingTimeInSeconds: 67649,
      remainingTimeForInstantPurchaseInSeconds: null,
      isRejectionWaitPeriodOver: false,
      amIRegularBuyer: true,
      distanceToVehicleInKms: 4041,
      isMinAskReached: false,
      enforceTransportation: false,
      isTransportationAvailable: true,
      amIHighestBidder: false,
      sellerContact: null,
      rating: null,
      transportationTask: null,
      isTransportationAllowedForRegion: true,
      isExternalPaymentAllowed: true,
      pickupPinCode: null,
      remainingDaysUntilReauctioning: null,
      remainingDaysUntilLatePickup: null,
      latePickupFee: null,
      isTransportationBookingPossible: true,
      isExpressPickupAvailable: true,
      pickupPossibleInDays: null,
      sellerAccount: {
          uuid: faker.datatype.uuid(),
          name: faker.name.findName()
      },
      associatedVehicle: {
        id: faker.datatype.number(),
        ez: "10/1979",
        make: faker.vehicle.manufacturer(),
        mileageInKm: 725736,
        model: faker.vehicle.model(),
        vin: faker.vehicle.vin(),
        hadAccident: false,
        accidentDescription: null,
        category: 6,
        doors: -1,
        enginePowerInHp: 268,
        engineSizeInCcm: 1364,
        fuelType: 3,
        transmission: 1,
        upholstery: 3,
        ac: 2,
        coupling: 2,
        headlights: 2,
        navigation: 1,
        parkingAssistance: 3,
        sportPackage: 0,
        sunRoof: 1,
        vehicleHeater: -1,
        huReportExists: false,
        lastHu: "09/2021",
        numKeys: 2,
        numPreOwners: 3,
        vatIdReportable: false,
        urlToAttachment1: null,
        urlToAttachment2: null,
        urlToAttachment3: null,
        additionalDamages: null,
        urlToVehicleSummarySheet: "https://res.cloudinary.com/castle-tech-gmbh-dev/image/upload/v1623746567/tpg7iwdoqw0dbk7gw67z.pdf",
        euroNorm: "R7oKgXbpÄAgÖA3TY",
        dimensionWidthInCm: null,
        dimensionHeightInCm: null,
        dimensionLengthInCm: null,
        unloadedWeightInKg: null,
        numSeats: 3,
        isReimportedVehicle: false,
        datBaseModelRaw: null,
        seriesEquipments: [],
        specialEquipments: [],
        uuid: faker.datatype.uuid(),
        origin: -1,
        dataSource: -1,
        createdAt: "2021-06-15T08:42:46.343Z",
        updatedAt: "2021-06-15T08:42:48.221Z",
        deletedAt: null,
        lastServiceInspectionDate: "10/1891",
        lastServiceInspectionMileage: 235344,
        isCocDocumentAvailable: false,
        countryOfLastRegistration: null,
        bodyColorCode: 11,
        readyToDrive: 0,
        readyToDriveDetails: null,
        hasDamages: false,
        damagesDescription: null,
        additionalInfo: null,
        dataWarnings: [],
        serviceHistoryAvailability: -1,
        fullServiceHistoryType: 3,
        hasMaintenanceBook: false,
        attachments: [],
        damages: [],
        equipmentData: [],
        equipmentHighlights: [
            {
                rank: 10,
                description: "Head-up-Display",
                category: 5
            },
            {
                rank: 145,
                description: "Airbag, Fahrer-/Beifahrerseite",
                category: 3
            }
        ],
        vehicleImages: [
            {
                url: "https://res.cloudinary.com/castle-tech-gmbh-dev/image/upload/v1615660854/test-data/0_nqua3q.jpg",
                perspective: 0
            }
        ],
        tires: [],
        paintState: [],
        technicalState: []
    }
    });
  }
  return fakeArray;
}